# All paths in settings translate {user} to be the user's home directory.
# In Windows this is "C:/Users/your_name/" and in Linux, "/home/your_name/".
# Paths are case-insensitive.
settings:

  # Where to keep torrents that are downloading or seeding. Default is a
  # subdirectory of the user's downloads directory.
  downloads: '{user}/downloads/nab'

  # a list of directories where videos are stored. The first of these is where
  # new downloaded videos are copied to when they are complete.
  # The default is the user's videos directory.
  videos:
    - '{user}/videos'
            

# How to find episodes that you own, have watched and want to follow.
# Uses two kinds of plugins: 'show source' and 'show filter'. 
# Both 'library' and 'following' accept 'show source' plugins, while 'filters' 
# takes 'show filter' plugins.
shows:

  # A list of 'source' plugins for episodes that you own or have watched.
  library:
    # The filesystem plugin, which looks for all video files in your video
    # directories (in "settings: videos" above) and marks them as 'owned'.
    - filesystem

  # A list of 'show source' plugins for finding shows that you want to watch.
  # Because this also takes 'show source' plugins, it can use any plugin in
  # 'library'. For example, the 'filesystem' plugin can be put here to 
  # automatically download any missing episodes of shows you already own.
  following:
    # The watchlist plugin gets shows from the watchlist file, which is stored
    # in the user's config directory:
    #   Windows: C:/Users/your_name/AppData/Local/nab/watchlist.txt
    #   Linux:   /home/your_name/.config/nab/watchlist.txt
    # Each row of the file should indicate a show, season or episode to follow.
    - watchlist

  # A list of 'show filter' plugins for episodes you don't want to download.
  filters:
    # Don't download specials (only numbered episodes).
    - specials
    # Don't download episodes you've already watched.
    - watched
    # Don't download episodes you already own.
    - owned


# A list of 'database' plugins for finding data about shows.
databases:
  # Looks up shows on thetvdb, which contains data on most TV shows.
  - tvdb
  # Look up shows on anidb. Has some additional information about alternate
  # show titles and season titles that make downloading anime possible.
  - anidb


# How to find torrent files for episodes that you want.
files:

  # A list of 'file source' plugins for finding torrents for episodes.
  sources:

    # EZTV torrent, good for high-quality, recent, single-episode torrents.
    - feed:
        name: EZTV
        url: http://ezrss.it/search/index.php?simple&show_name={s}&show_name_exact=true&mode=rss
        search_by:
          - show

    # Kickass Torrents, good for just about everything.
    - feed:
        name: Kickass Torrents
        url: "https://kickass.so/usearch/{s}%20category%3Atv/{p}/?field=seeders&sorder=desc&rss=1"

    # Nyaa, good for anime.
    - feed:
        name: Nyaa
        url: http://www.nyaa.se/?page=rss&cats=1_37&term={s}&offset={p}

  # A list of 'file filter' plugins for choosing which torrent to download.
  # Any filter which lists preferences including 'Other' means 
  # 'any other file not matching something in this list'.
  # If 'Other' is omitted, then files will be rejected if they don't match
  # something on the list.
  filters:

    # Ranks based on release group.
    groups:
      - DIMENSION
      - LOL
      - 2HD
      - FQM
      - DHD
      - ORENJI
      - KILLERS
      - Other

    # Ranks based on fansub group.
    fansubs:
      - HorribleSubs
      - Commie
      - DeadFish
      - CoalGirls
      - UTW
      - Mazui
      - gg
      - Other

    # Ranks based on resolution.
    quality:
      - 1080p
      - 720p
      - Other
      - 480p
      - 360p

    # Ranks based on video source.
    source:
      - BluRay
      - Other
      - DVD
      - TV

    # Ranks based on video encoding.
    encoding:
      - h264
      - Other
      - Xvid

    # Weighted rank based on number of seeds. This is the most important thing,
    # so it is given five times higher weighting compared to other filters.
    weighted:
      weight: 5.0
      filters:
        - seeds


# The 'downloader' plugin to use. There are other plugins available that
# connect to your installed torrent client, such as uTorrent.
downloader:
  
  # By default, download using libtorrent, which is a built-in torrent cilent.
  libtorrent


# Settings for renaming and copying files to the video directory.
renamer:

  # Pattern to use when renaming files. Keywords that will be converted are:
  # {videos}    Videos directory
  # {t}         Show title
  # {st}        Season title (usually the same as the show title)
  # {s}         Season number
  # {e}         Episode number
  # {et}        Episode title
  pattern: '{videos}/{t}/{st} - S{s}E{e} - {et}'

  # 'yes' means copy to the videos directory, 'no' means move, don't copy.
  # This is yes by default because it allows the torrent client to seed.
  copy: yes
