settings:
  downloads: '{user}\downloads\nab'
  videos:
    - '{user}\videos'
shows:
  library:
    - filesystem
  watching:
    - watchlist
  filters:
    - specials
    - watched
    - owned
databases:
  - tvdb
  - anidb
files:
  sources:
    - feed:
        name: EZTV
        url: http://ezrss-proxy.net/search/index.php?simple&show_name={s}&show_name_exact=true&mode=rss
        search_by:
          - show
    - feed:
        name: Kickass Torrents
        url: "http://kickassto.come.in/usearch/{s}%20category%3Atv/{p}/?field=seeders&sorder=desc&rss=1"
    - feed:
        name: Nyaa
        url: http://www.nyaa.se/?page=rss&cats=1_37&term={s}&offset={p}
  filters:
    groups:
      - DIMENSION
      - LOL
      - 2HD
      - FQM
      - DHD
      - ORENJI
      - KILLERS
      - Other
    fansubs:
      - HorribleSubs
      - Commie
      - DeadFish
      - CoalGirls
      - UTW
      - Mazui
      - gg
      - Other
    quality:
      - 1080p
      - 720p
      - Other
      - 480p
      - 360p
    source:
      - BluRay
      - Other
      - DVD
      - TV
    encoding:
      - h264
      - Other
      - Xvid
    weighted:
      weight: 5.0
      filters:
        - seeds
downloader:
  libtorrent
renamer:
  pattern: '{videos}\{t}\{st} - S{s:02d}E{e:02d} - {et}'
  copy: yes
